jettyXmlFiles=jetty-bytebufferpool.xml,jetty-threadpool.xml,jetty.xml
jettyHttpXmlFiles=jetty.xml
jettyHttpsXmlFiles=jetty-ssl.xml,jetty-ssl-context.xml,jetty-https.xml
httpEnabled=true
httpsEnabled=false
jetty.http.port=9090
jetty.ssl.port=9443
jetty.httpConfig.securePort=9443
jetty.sslContext.keyStorePassword=OBF:1vny1zlo1x8e1vnw1vn61x8g1zlu1vn4